# Generated by Django 4.2.7 on 2023-11-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Electronic',
        ),
        migrations.DeleteModel(
            name='Gospel',
        ),
        migrations.DeleteModel(
            name='HipHop_Rap',
        ),
        migrations.DeleteModel(
            name='Jazz',
        ),
        migrations.DeleteModel(
            name='Pop',
        ),
        migrations.DeleteModel(
            name='Reggae',
        ),
        migrations.DeleteModel(
            name='RnB',
        ),
        migrations.DeleteModel(
            name='Rock',
        ),
    ]
