# Generated by Django 4.2.7 on 2023-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champions_League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='English_Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Germany_Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Spanish_Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='all_sport',
            name='game',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
    ]
