# Generated by Django 4.2.7 on 2023-11-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alopehomeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
