# Generated by Django 4.2.7 on 2023-11-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_category_delete_action_delete_drama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
